templates:
  - name: Feature
    about: Submit a new feature
    filename: PULL_REQUEST_TEMPLATE/feature.md
  - name: Bug fix
    about: Submit a bug fix
    filename: PULL_REQUEST_TEMPLATE/bugfix.md
  - name: Performance improvement
    about: Submit a performance improvement
    filename: PULL_REQUEST_TEMPLATE/performance.md
  - name: Refactoring
    about: Submit a code refactoring
    filename: PULL_REQUEST_TEMPLATE/refactoring.md
  - name: Documentation
    about: Submit documentation changes
    filename: PULL_REQUEST_TEMPLATE/documentation.md
  - name: Dependency update
    about: Submit dependency updates
    filename: PULL_REQUEST_TEMPLATE/dependency.md
  - name: CI/CD changes
    about: Submit CI/CD pipeline changes
    filename: PULL_REQUEST_TEMPLATE/ci_cd.md
  - name: Configuration changes
    about: Submit configuration changes
    filename: PULL_REQUEST_TEMPLATE/config.md